services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gerenciador_estoque:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  data:
    driver: local