spring.application.name=gerenciador_estoque
# ===============================
# DATASOURCE desativado (PostgreSQL)
# ===============================
# spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
# spring.datasource.username=${DB_USER:postgres}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=("driver do banco de dados")
# ===============================
# DATASOURCE (SQLite)
# ===============================
spring.datasource.url=jdbc:sqlite:./data/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
server.servlet.context-path=/api
# ===============================
# SERVER
# ===============================
server.port=${SERVER_PORT:8080}
# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:fe42eedc19ad68c4db975dd5ba6d52d0da47387b40af9e4093d6f8cb3a47a933}
jwt.expiration=${JWT_EXPIRATION:86400000}
# ===============================
# SWAGGER / OPEN-DOC
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
